const CITIES = [
  {
    country: 'AU',
    countryName: 'Australia',
    cities: [
      {
        name: 'Gold Coast',
        cityId: 61030900,
        countyId: 0,
        activityId: '102602020',
        activityType: 26,
        discount: '50% off ($15 max) x 2',
        referrer: '$10 x 2 + $10 x 2',
        tz: 'Australia/Brisbane',
      },
      {
        name: 'Newcastle',
        cityId: 61011100,
        countyId: 0,
        activityId: '102602020',
        activityType: 26,
        discount: '50% off ($15 max) x 2',
        referrer: '$10 x 2 + $10 x 2',
        tz: 'Australia/Sydney',
      },
      {
        name: 'Perth',
        cityId: 61050200,
        countyId: 0,
        activityId: '102602022',
        activityType: 26,
        discount: '50% off ($15 max) x 2',
        referrer: '$10 x 2 + $10 x 2',
        tz: 'Australia/Perth',
      },
      {
        name: 'Adelaide',
        cityId: 61040100,
        countyId: 0,
        activityId: '102602021',
        activityType: 26,
        discount: '$5 off x 4',
        referrer: '$5 + $5',
        tz: 'Australia/Adelaide',
      },
      {
        name: 'Ballarat',
        cityId: 61020100,
        countyId: 0,
        activityId: '102602021',
        activityType: 26,
        discount: '$5 off x 4',
        referrer: '$5 + $5',
        tz: 'Australia/Melbourne',
      },
      {
        name: 'Bendigo',
        cityId: 61020200,
        countyId: 0,
        activityId: '102602021',
        activityType: 26,
        discount: '$5 off x 4',
        referrer: '$5 + $5',
        tz: 'Australia/Melbourne',
      },
      {
        name: 'Brisbane',
        cityId: 61030100,
        countyId: 0,
        activityId: '102602021',
        activityType: 26,
        discount: '$5 off x 4',
        referrer: '$5 + $5',
        tz: 'Australia/Brisbane',
      },
      {
        name: 'Bundaberg - Hervey Bay',
        cityId: 61031900,
        countyId: 0,
        activityId: '102602021',
        activityType: 26,
        discount: '$5 off x 4',
        referrer: '$5 + $5',
        tz: 'Australia/Brisbane',
      },
      {
        name: 'Bunbury - Busselton',
        cityId: 61050100,
        countyId: 0,
        activityId: '102602021',
        activityType: 26,
        discount: '$5 off x 4',
        referrer: '$5 + $5',
        tz: 'Australia/Perth',
      },
      {
        name: 'Cairns',
        cityId: 61030600,
        countyId: 0,
        activityId: '102602021',
        activityType: 26,
        discount: '$5 off x 4',
        referrer: '$5 + $5',
        tz: 'Australia/Brisbane',
      },
      {
        name: 'Canberra',
        cityId: 61080100,
        countyId: 0,
        activityId: '102602021',
        activityType: 26,
        discount: '$5 off x 4',
        referrer: '$5 + $5',
        tz: 'Australia/Sydney',
      },
      {
        name: 'Central Coast',
        cityId: 61010200,
        countyId: 0,
        activityId: '102602021',
        activityType: 26,
        discount: '$5 off x 4',
        referrer: '$5 + $5',
        tz: 'Australia/Sydney',
      },
      {
        name: 'Coffs Harbour',
        cityId: 61010400,
        countyId: 0,
        activityId: '102602021',
        activityType: 26,
        discount: '$5 off x 4',
        referrer: '$5 + $5',
        tz: 'Australia/Sydney',
      },
      {
        name: 'Geelong',
        cityId: 61020300,
        countyId: 0,
        activityId: '102602021',
        activityType: 26,
        discount: '$5 off x 4',
        referrer: '$5 + $5',
        tz: 'Australia/Melbourne',
      },
      {
        name: 'Mackay',
        cityId: 61031200,
        countyId: 0,
        activityId: '102602021',
        activityType: 26,
        discount: '$5 off x 4',
        referrer: '$5 + $5',
        tz: 'Australia/Brisbane',
      },
      {
        name: 'Melbourne',
        cityId: 61020600,
        countyId: 0,
        activityId: '102602021',
        activityType: 26,
        discount: '$5 off x 4',
        referrer: '$5 + $5',
        tz: 'Australia/Melbourne',
      },
      {
        name: 'Port Macquarie',
        cityId: 61010800,
        countyId: 0,
        activityId: '102602021',
        activityType: 26,
        discount: '$5 off x 4',
        referrer: '$5 + $5',
        tz: 'Australia/Sydney',
      },
      {
        name: 'Rockhampton - Gladstone',
        cityId: 61030800,
        countyId: 0,
        activityId: '102602021',
        activityType: 26,
        discount: '$5 off x 4',
        referrer: '$5 + $5',
        tz: 'Australia/Brisbane',
      },
      {
        name: 'Shepparton - Mooroopna',
        cityId: 61021600,
        countyId: 0,
        activityId: '102602021',
        activityType: 26,
        discount: '$5 off x 4',
        referrer: '$5 + $5',
        tz: 'Australia/Melbourne',
      },
      {
        name: 'Sunshine Coast',
        cityId: 61031600,
        countyId: 0,
        activityId: '102602021',
        activityType: 26,
        discount: '$5 off x 4',
        referrer: '$5 + $5',
        tz: 'Australia/Brisbane',
      },
      {
        name: 'Sydney',
        cityId: 61011500,
        countyId: 0,
        activityId: '102602021',
        activityType: 26,
        discount: '$5 off x 4',
        referrer: '$5 + $5',
        tz: 'Australia/Sydney',
      },
      {
        name: 'Toowoomba',
        cityId: 61031700,
        countyId: 0,
        activityId: '102602021',
        activityType: 26,
        discount: '$5 off x 4',
        referrer: '$5 + $5',
        tz: 'Australia/Brisbane',
      },
      {
        name: 'Townsville',
        cityId: 61031800,
        countyId: 0,
        activityId: '102602021',
        activityType: 26,
        discount: '$5 off x 4',
        referrer: '$5 + $5',
        tz: 'Australia/Brisbane',
      },
      {
        name: 'Wagga Wagga',
        cityId: 61011300,
        countyId: 0,
        activityId: '102602021',
        activityType: 26,
        discount: '$5 off x 4',
        referrer: '$5 + $5',
        tz: 'Australia/Sydney',
      },
      {
        name: 'Wollongong',
        cityId: 61010700,
        countyId: 0,
        activityId: '102602021',
        activityType: 26,
        discount: '$5 off x 4',
        referrer: '$5 + $5',
        tz: 'Australia/Sydney',
      },
    ],
  },
];
